tasks:
  - name: pythonUpgrade
    init: |
      pyenv install 3.9.14
      pyenv local 3.9.14
      pip install --upgrade pip
      gp sync-done pythonupgrade
  - name: uvicorn
    init: |
      gp sync-await pythonupgrade
      pip install -r requirements.txt
    command: uvicorn main:app --reload

ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python